### ISSUE TITLE
Menu de header tapa el título de los posts en algunos displays (ni tamaño celular ni computadora grande)

### ISSUE THREAD

**Issue by FdelMazo** [algoritmos-rw/algo2#206]
Ejemplo en un display de 1000x800 (falta el título 'TP0')

![image](https://user-images.githubusercontent.com/25667102/45256206-88088d80-b369-11e8-983d-d2dfc7b47f67.png)

**Comment by JDSanto** [comment]
#306 volvió a romper esto.

Habría que ver de sacar algún botón (infraestructura), mover otro al menú de alumnos (encuestas) o crear otro menú como el de alumnos.
![image](https://user-images.githubusercontent.com/4763786/61259568-3252fd80-a751-11e9-9fbd-c7ac4344db0e.png)

**Comment by mbuchwald** [comment]
Que raro, yo había probado cambiar el ancho y cambiaba a cómo se ve en mobile

**Comment by JDSanto** [comment]
Hay un rango de resoluciones donde se rompe, antes de que cambie a la "interfaz" de mobile.
El del screenshot es el peor caso, porque _dos_ botones bajan en vez de uno, así que esta vez no alcanzaría con reducir el tamaño entre los botones.

**Comment by mbuchwald** [comment]
Y si solo dejamos los iconos (que el texto aparezca como alt) y que el texto completo se vea solo en la versión mobile?

**Comment by FdelMazo** [comment]
También se puede:
- Cambiar el media query que achica el navtab para mobile, haciendo que se convierta en menu desplegable mucho antes
- Sacar algun item del menu (poner la bibliografia en el inicio, y fue...)
- Ponerle más padding top al contenido del sitio, pero tiene que adaptarse a la pantalla porque si no en mobile va a quedar horrible

**Comment by mbuchwald** [comment]
El tema es que si sacamos, habría que ver a dónde lo metemos (una sección de extras?). Y además pensaba agregar algunas cosas a ese header en el próximo PR, pero esto podría ser un problema de sobrepoblación. Ahora le doy alguna vuelta de tuerca a ver si se puede dejar mejor esto

**Comment by mbuchwald** [comment]
Bueno, encontré una forma de distribuirlos mejor, pero... siempre existe alguna resolución para la cual se caga.... 🤷‍♂ post charla del viernes mando el PR (porque cambia bastantes cosas)

**Comment by JDSanto** [comment]
Arreglado en #307
