### ISSUE TITLE
Acerca de la lista ( foro de Google groups)

### ISSUE THREAD

**Issue by Savantage** [algoritmos-rw/algo2#224]
Hola,

No sé si hay un poder de personalización departe del dueño del foro, pero marea un poco a veces, diferenciar consultas de alumnos de anuncios de la cátedra y demás, sin tener que revisar el contenido, lo cual es muy desalentador a la hora de usar el grupo. De ser posible, estaría buenísimo crear Flags, o si se pudiera dividir en secciones, sería mucho más user friendly.

**Comment by mbuchwald** [comment]
En sí no es un foro, sino una lista de mails, así que no existe esa posibilidad. Estaría bueno tener ese tipo de posibilidades, pero lamentablemente no lo tenemos. 
> Entonces por qué no migran a un foro? 
Tenemos dos razones, principalmente: 
1. Tenemos todo un historial de mails que _se perderían_ (no se volverían a chequear). 
2. En un foro (al menos las opciones que evaluamos) no tenemos la posibilidad de que se mande todo por mail. Hasta ahora siempre tuvimos más resultados positivos y más actividad en la lista porque a todos nos llega un mail (docentes y alumnos). Lease de otra forma: mi mail lo tengo abierto en general, pero el foro no lo abriría seguido. 

Se evaluaron otras opciones como github classroom (no recuerdo el nombre exacto) pero se descartó porque la idea no es agregar un nivel más de complejidad a la cantidad de cosas que deben aprender para la materia, y más desde el inicio (porque la lista es a lo primero que acceden). Ya tienen bastante con gcc, gdb, valgrind, linux, familiarizarse con la terminal y, si alguno se anima, usar un sistema de control de versiones. Sin contar la cantidad de tps que tienen que implementar.
