### ISSUE TITLE
Material sobre C.

### ISSUE THREAD

**Issue by santisis** [algoritmos-rw/algo2#281]
No sé si alguno se dio cuenta pero todo el material de C está subido por duplicado.

Por un lado hay "apuntes" sueltos, por el otro lado está subido el apunte "Introducción al lenguaje C" cuyo fuente contiene:

```tex
\include{lenguaje_c}
\include{memoria_dinamica}
\include{vectores}
\include{parametros}
\include{merge_sort}
\include{quick_sort}
\include{makefile}
\include{archivos}
```

es decir, el texto de C de 47 páginas es lo mismo que está subido como apuntes sueltos.

Propongo verificar si hay algún apunte que no esté incluido en el apunte grande (y si no lo está agregarlo, eso es para el repo algo2_apuntes) y eliminar de la página de la materia el contenido que sean capítulos del apunte sueltos.

**Comment by FdelMazo** [comment]
Está bien esto @santisis ? Es como está estructurado el apunte de algoritmos 1.

* Primera pág:
     "Algoritmos y Programación II"
     "Introducción al Lenguaje C (o simplemente 'el lenguaje C')"

* Índice
* Apunte en sí
* Ultíma pagina de copyright (acá que va? creative commons?)

**Comment by santisis** [comment]
Sigámosla por acá, corresponde a este repo: https://github.com/algoritmos-rw/algo2_apuntes/issues/9

**Comment by santisis** [comment]
> Está bien esto @santisis ? Es como está estructurado el apunte de algoritmos 1.
> 
> * Primera pág:
>   "Algoritmos y Programación II"
>   "Introducción al Lenguaje C (o simplemente 'el lenguaje C')"
> * Índice
> * Apunte en sí
> * Ultíma pagina de copyright (acá que va? creative commons?)

Sí, la licencia es CC, está la nota de copyright como comentario en el fuente LaTeX:

```tex
% Copyright (C) 2010-2013, Maximiliano Curia <maxy@gnuservers.com.ar>,
%               2010-2013, Margarita Manterola <marga@marga.com.ar>

% Esta obra está licenciada de forma dual, bajo las licencias Creative
% Commons:
%  * Atribución-Compartir Obras Derivadas Igual 2.5 Argentina
%    http://creativecommons.org/licenses/by-sa/2.5/ar/
%  * Atribución-Compartir Obras Derivadas Igual 3.0 Unported
%    http://creativecommons.org/licenses/by-sa/3.0/deed.es_AR.
%
% A su criterio, puede utilizar una u otra licencia, o las dos.
% Para ver una copia de las licencias, puede visitar los sitios
% mencionados, o enviar una carta a Creative Commons,
% 171 Second Street, Suite 300, San Francisco, California, 94105, USA.
```

Sobre el esquema que proponés, está bien para mí. Lo único importante importante es que quede en claro que es un apunte de la cátedra. Y sí, siendo que del apunte inicial del lenguaje se agregaron tantos capítulos está bueno que haya una tabla de contenidos al comienzo.
