### ISSUE TITLE
Generar y publicar de manera automática el PDF de las guías

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/algo2#344]
No es muy prioritario pero… se debería poder hacer fácilmente con Github Actions.

**Comment by mbuchwald** [comment]
Dejo por acá el comentario que hice en slack: 
> La unica razon para sacarlo de gh (como tenia puesto originalmente en el pr) es porque justamente era propenso olvidarse de generarse, o bien no permitáa simplemente ir y crear un pr desde la web y listo (sin tener que mandar luego ooootro pr). Si se genera automático me parece bien sacarlo del drive (tenerlo en dos lugares generaría confusión)
