### ISSUE TITLE
Añadir entrada a la FAQ sobre strtol

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/algo2#355]
Si vamos a seguir haciendo calculadora, quizás sea una buena idea hacer un refrito en la FAQ [de este post sobre strtol](https://groups.google.com/d/msg/fiuba-7541rw-alu/HmHqW1FBp-0/Poku0XT6aFcJ).

**Comment by mbuchwald** [comment]
Si, y no solo eso: hay que dejar en el _template de tp1_ ya el link al FAQ y poner en negrita: *Leer la FAQ antes de comenzar con el desarrollo*. Algunas preguntas aparecen todos los cuatrimestres (ej: por qué no compila getline, etc.)

**Comment by mbuchwald** [comment]
Cierro esto ya que ahora no usaríamos más C
