### ISSUE TITLE
Unificar en un solo sitio el listado de flags de GCC

### ISSUE THREAD

**Issue by dato** [algoritmos-rw/algo2#364]
Me gustaría que la definición _canónica_ de los flags que usa la corrección, esté en el sitio web; y que si hay una discrepancia con el corrector, el sitio web tenga razón.

Esto nos protege frente a realizar cambios en en el corrector sin avisar a les alumnes; y también alivia al corrector de tener que imprimir la invocación exacta que usó.

Ahora mismo cuento en el repo 24 instancias de `-std=` y `-Wall`; 13 de `-Werror`; y 4 de `-Wshadow` y `-Wbad-function-cast`, que también usamos. Convendría centralizar en un solo sitio la lista, que por cierto es:

```
CFLAGS := -g -O2 -std=gnu18 -Wall -pedantic -Wformat=2
CFLAGS += -Wshadow -Wpointer-arith -Wunreachable-code
CFLAGS += -Wconversion -Wno-sign-conversion -Wbad-function-cast
```

Más algún override como `-Wno-conversion` en el tp1 para hacer fácil la implementación de _dc_. (Estoes se pueden documentar adicionalmente en la consigna que corresponda.)

(**Respecto a `-Werror`,** personalmente me debato si la debemos incluir _en la página_. Con decir "el código subido tiene que compilar sin warnings", está claro que la entrega no se acepta si tiene warnings [porque nosotros sí compilamos con `-Werror`]. Es un arma de doble filo no decírsela explícitamente: tiene a su favor que hace menos frustrante el desarrollo; pero también hay veces que lo que están intentando a arreglar... se debe a un warning que están ignorando. Pero capaz así se acostumbren mejor a _leerlos_, en lugar de odiarlos.)

**Comment by mbuchwald** [comment]
Al no usar más C, cerramos este issue
