### ISSUE TITLE
Link Roto

### ISSUE THREAD

**Issue by tomdv18** [algoritmos-rw/algo2#368]
Hola! Estaba navegando en la página de la materia, investigando como funciona makefile para el TP1
Estaba en la siguiente página https://algoritmos-rw.github.io/algo2/faq/compilacion-ejecucion/#qu%C3%A9-es-un-archivo-makefile
Cuando en la sección que habla sobre MAKEFILE hay un link que supuestamente me llevaria a un apunte de la página pero cuando intento ingresar me salta un error 404
No se si es la manera correcta de informar esto, mil disculpas, nunca use GitHub

**Comment by dato** [comment]
Sí, esta es la vía para informar de errores en la página, lo has hecho perfectamente.

_Creo_ que el link debiera ser este: https://docs.google.com/presentation/d/1Ok1jAKLFOO4pzOQA6eK2yQgIEuFOzC_yjvFeFw_FCm8/edit#slide=id.g36999ae2ec_2_80

Cuando @mbuchwald lo confirme, lo corregiremos en la página.

¡Saludos!

**Comment by mbuchwald** [comment]
Si! Debería ser esa! Seguro quedó mal de alguna actualización
